/*
   Copyright (c) 2021 Christof Ruch. All rights reserved.

   Dual licensed: Distributed under Affero GPL license by default, an MIT license is available for purchase
*/

#pragma once

#define LAYOUT_INSET_SMALL 4
#define LAYOUT_INSET_NORMAL 8

#define LAYOUT_LINE_HEIGHT 24
#define LAYOUT_LINE_SPACING (LAYOUT_LINE_HEIGHT + LAYOUT_INSET_NORMAL)

#define LAYOUT_TEXT_LINE_HEIGHT 24
#define LAYOUT_TEXT_LINE_SPACING (LAYOUT_TEXT_LINE_HEIGHT + LAYOUT_INSET_SMALL)

#define LAYOUT_LARGE_LINE_HEIGHT 36
#define LAYOUT_LARGE_LINE_SPACING (LAYOUT_LARGE_LINE_HEIGHT + LAYOUT_INSET_NORMAL)

#define LAYOUT_SMALL_ICON_WIDTH 32
#define LAYOUT_SMALL_ICON_HEIGHT 32

#define LAYOUT_CHECKBOX_WIDTH 128
#define LAYOUT_BUTTON_WIDTH 128
#define LAYOUT_BUTTON_WIDTH_MIN 64

#define LAYOUT_LARGE_FONT_SIZE 24.0f


